coverage:
	python -m pytest -v --cov-report term-missing --cov=project/

test:
	python -m pytest

list-requirements:
	pip freeze

install-requirements:
	pip install -r requirements.txt

run-aplication:
	python setup.py

